# oops-mesa - what `./bin/oops-mesa` runs. The verbs live in bin/; the mechanics live here.
#
# Only `check` and `clean` exist today. `check` is everything CI can answer without a
# container or the hardware. The container build arrives with roadmap unit 3 and is added
# here, not in a second Makefile.

include dependencies.mk

.PHONY: check check-pin check-patches check-docs check-format check-preamble check-tiling preamble tiling test clean

check: check-pin check-patches check-docs check-format check-preamble check-tiling
	@echo "oops-mesa: check passed (pin $(MESA_TAG), $(words $(wildcard patches/*.patch)) patches)"

# The submodule is present and at exactly the commit the pin names. A tree whose Mesa is on
# some other commit builds something the patches and the hardware tests were never run
# against, so it fails here rather than later.
check-pin:
	@test -f mesa/meson.build || { echo "oops-mesa: mesa/ is empty; run: git submodule update --init --depth 1" >&2; exit 1; }
	@actual=$$(git -C mesa rev-parse HEAD); \
	 if [ "$$actual" != "$(MESA_PIN)" ]; then \
	   echo "oops-mesa: mesa/ is at $$actual, dependencies.mk pins $(MESA_PIN) ($(MESA_TAG))" >&2; exit 1; \
	 fi

# Every patch explains itself. A patch file that does not start with a comment block saying
# what it changes and why a shim could not carry it is refused (CLAUDE.md, principle 1).
check-patches:
	@for p in $(wildcard patches/*.patch); do \
	   head -1 "$$p" | grep -q '^#' || { echo "oops-mesa: $$p has no header comment" >&2; exit 1; }; \
	 done

# The documents the conventions require, and the generated decision index matching its files.
check-docs:
	@for f in README.md CLAUDE.md ACKNOWLEDGEMENTS.md CHANGELOG.md docs/DECISIONS.md docs/ROADMAP.md docs/WORKLOG.md docs/decisions/_preamble.md; do \
	   test -f "$$f" || { echo "oops-mesa: missing $$f" >&2; exit 1; }; \
	 done
	@for d in docs/decisions/D*.md; do \
	   n=$$(basename "$$d" | cut -d- -f1); \
	   grep -q "| $$n |" docs/DECISIONS.md || { echo "oops-mesa: $$d is not in docs/DECISIONS.md; run tools/split-decisions.sh --index oops-mesa from the collection root" >&2; exit 1; }; \
	 done

# First-party C and C++ matches .clang-format, checked in the pinned compiler image.
check-format:
	@bash tools/format.sh --check

# tools/preamble-dump: the command-stream preamble radeonsi would emit for this hardware, as
# data generated by the pinned Mesa. Its two outputs are tracked, so a pin bump that changes
# the preamble is visible in the diff; this target regenerates into build/ and compares.
# Needs python3 and clang (the WSL builder has both) and is skipped, not failed, without them.
check-preamble:
	@if command -v clang >/dev/null && command -v python3 >/dev/null; then \
	   bash tools/preamble-dump/build.sh --check; \
	 else \
	   echo "oops-mesa: check-preamble skipped (needs clang and python3 on PATH)"; \
	 fi

preamble:
	bash tools/preamble-dump/build.sh

# tools/tiling-compare: whether a radeonsi 64KB_R_X surface lands in the same bytes as the layout
# oops-sdk's tiler produces, which is what the display scans out. Its tracked output carries the
# verdict *and* a control, so an agreement that stops meaning anything is visible. Needs clang++
# and a sibling oops-sdk; skipped, not failed, without them.
check-tiling:
	@if command -v clang++ >/dev/null && test -d $(OOPS_SDK)/src/agc; then \
	   OOPS_SDK=$(OOPS_SDK) bash tools/tiling-compare/build.sh --check; \
	 else \
	   echo "oops-mesa: check-tiling skipped (needs clang++ and an oops-sdk at $(OOPS_SDK))"; \
	 fi

tiling:
	OOPS_SDK=$(OOPS_SDK) bash tools/tiling-compare/build.sh

clean:
	rm -rf build dist

# The shims' host suite. It runs on the build machine with OOPS_HOST_BUILD, so it exercises what
# this repository decides rather than what the hardware does: the device description's values and
# provenance, and that an unimplemented command refuses instead of quietly succeeding.
#
# oops-sdk is a sibling checkout, named by a variable rather than assumed, because it lives
# outside this repository - the same shape the FreeBSD checkout uses (D004).
OOPS_SDK ?= ../oops-sdk

test:
	@test -d $(OOPS_SDK)/include || { echo "oops-mesa: no oops-sdk at $(OOPS_SDK); set OOPS_SDK" >&2; exit 1; }
	@mkdir -p build/host
	@cc -std=c11 -Wall -Wextra -Werror -DOOPS_HOST_BUILD \
	    -Imesa/include -Imesa/src -Isrc/winsys -I$(OOPS_SDK)/include \
	    tests/winsys_test.c tests/platform_double.c src/winsys/drm_device.c src/winsys/device_info.c src/winsys/buffers.c src/winsys/submit.c src/winsys/context.c src/winsys/log.c src/winsys/syncobj.c \
	    $(OOPS_SDK)/src/memory/memory.c \
	    -o build/host/winsys_test
	@./build/host/winsys_test
	@#
	@# The runtime shim gets its own binary, because `stderr_to_klog.c` defines `fprintf`,
	@# `fwrite`, `fputs`, `fputc`, `puts`, `fflush` and `perror`. Linking it into the suite above
	@# would redirect that suite's own reporting into the log sink, and it would pass silently.
	@cc -std=c11 -Wall -Wextra -Werror -DOOPS_HOST_BUILD \
	    -Isrc/runtime \
	    tests/runtime_test.c \
	    -o build/host/runtime_test
	@./build/host/runtime_test
