/* preamble-dump: print the command-stream preamble Mesa's AMD driver would emit for this
 * hardware, as data.
 *
 * This is the input to roadmap unit 2 (D003): the register set radeonsi writes at the start
 * of every command stream, generated by Mesa's own code at the pinned revision rather than
 * transcribed by hand, so the experiment measures what the driver actually does. The device
 * description below is what a Linux kernel would report; here it is the handful of fields the
 * generator reads, set from what is measured or public about the hardware:
 *
 *   gfx_level GFX10, family GFX1013   Mesa's own name for this silicon ("GFX10 plus ray
 *                                     tracing instructions", ac_gpu_info.c).
 *   address32_hi 0x2                  every GPU mapping this SDK has seen sits at
 *                                     0x2_0000_0000 (oops-sdk oracle record, 2026-09-14).
 *   max_se 2, max_render_backends 16  the Navi 10 shape the family shares; only the "more
 *   enabled_rb_mask 0xffff            than four render backends" branch depends on it.
 *   spi_cu_en 0xffff                  every compute unit enabled, as the SDK's own stage
 *                                     tables already run.
 *   pbb_max_alloc_count 128           ac_gpu_info's GFX10 formula: min(128, 1024 / (4 * 2)).
 *   has_clear_state true              GFX7 to GFX10 have CLEAR_STATE (ac_gpu_info.c).
 *
 * Two variants are printed: A begins with CONTEXT_CONTROL and CLEAR_STATE exactly as
 * radeonsi's gfx6_init_gfx_preamble_state does on a graphics queue without register
 * shadowing. B is the preamble for a device reported without CLEAR_STATE (has_clear_state
 * off): the same register writes, no CLEAR_STATE; radeonsi then treats every tracked register
 * as unknown and writes it through its normal state emission instead of trusting a default.
 * A measures whether the platform serves CLEAR_STATE; B measures the preamble on its own.
 *
 * Standard output is a C header holding the two streams. Standard error is the same streams
 * decoded packet by packet with Mesa's register names, for reading and for the worklog.
 */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "ac_gpu_info.h"
#include "ac_pm4.h"
#include "ac_cmdbuf.h"
#include "ac_debug.h"
#include "sid.h"

static void describe(struct radeon_info *info)
{
    memset(info, 0, sizeof(*info));
    info->gfx_level = GFX10;
    info->family = CHIP_GFX1013;
    info->has_graphics = true;
    info->has_clear_state = true;
    info->address32_hi = 0x2;
    info->max_se = 2;
    info->max_render_backends = 16;
    info->enabled_rb_mask = 0xffff;
    info->spi_cu_en = 0xffff;
    info->pbb_max_alloc_count = 128;
}

static struct ac_pm4_state *build(const struct radeon_info *info, bool clear_state)
{
    struct ac_pm4_state *pm4 = ac_pm4_create_sized(info, false, 512, false);
    const struct ac_preamble_state state = {0};

    /* radeonsi, gfx6_init_gfx_preamble_state: graphics queue, no kernel register shadowing. */
    ac_pm4_cmd_add(pm4, PKT3(PKT3_CONTEXT_CONTROL, 1, 0));
    ac_pm4_cmd_add(pm4, S_281_UPDATE_LOAD_ENABLES(1));
    ac_pm4_cmd_add(pm4, S_282_UPDATE_SHADOW_ENABLES(1));
    if (clear_state) {
        ac_pm4_cmd_add(pm4, PKT3(PKT3_CLEAR_STATE, 0, 0));
        ac_pm4_cmd_add(pm4, 0);
    }
    ac_init_compute_preamble_state(&state, pm4);
    ac_init_graphics_preamble_state(&state, pm4);
    /* si_init_graphics_preamble_state adds this on GFX7..GFX11. */
    ac_pm4_set_reg(pm4, R_02882C_PA_SU_PRIM_FILTER_CNTL,
                   S_02882C_XMAX_RIGHT_EXCLUSION(1) | S_02882C_YMAX_BOTTOM_EXCLUSION(1));
    ac_pm4_finalize(pm4);
    return pm4;
}

static void print_array(const char *name, const struct ac_pm4_state *pm4)
{
    printf("static const uint32_t %s[%u] = {\n", name, pm4->ndw);
    for (unsigned i = 0; i < pm4->ndw; i++) {
        if (i % 6 == 0) printf("   ");
        printf(" 0x%08xu,", pm4->pm4[i]);
        if (i % 6 == 5 || i + 1 == pm4->ndw) printf("\n");
    }
    printf("};\n\n");
}

/* Walk the stream as the command processor would and name each register it sets. Only the
 * three SET_*_REG forms the preamble uses are decoded; anything else is shown by opcode. */
static void print_decoded(const char *name, const struct ac_pm4_state *pm4)
{
    const struct radeon_info *info = pm4->info;
    unsigned regs = 0, packets = 0;

    fprintf(stderr, "== %s: %u dwords\n", name, pm4->ndw);
    for (unsigned i = 0; i < pm4->ndw;) {
        uint32_t hdr = pm4->pm4[i];
        unsigned count = PKT_COUNT_G(hdr) + 1;     /* data dwords after the header */
        unsigned op = PKT3_IT_OPCODE_G(hdr);
        unsigned base = 0;
        const char *kind = NULL;

        if ((hdr >> 30) != 3) {
            fprintf(stderr, "  %4u: 0x%08x  not a type-3 packet; stopping\n", i, hdr);
            break;
        }
        packets++;
        switch (op) {
        case PKT3_SET_CONTEXT_REG: base = SI_CONTEXT_REG_OFFSET; kind = "context"; break;
        case PKT3_SET_SH_REG:      base = SI_SH_REG_OFFSET;      kind = "sh";      break;
        case PKT3_SET_UCONFIG_REG: base = CIK_UCONFIG_REG_OFFSET; kind = "uconfig"; break;
        case PKT3_CONTEXT_CONTROL:
            fprintf(stderr, "  %4u: CONTEXT_CONTROL  load 0x%08x  shadow 0x%08x\n",
                    i, pm4->pm4[i + 1], pm4->pm4[i + 2]);
            break;
        case PKT3_CLEAR_STATE:
            fprintf(stderr, "  %4u: CLEAR_STATE\n", i);
            break;
        default:
            fprintf(stderr, "  %4u: opcode 0x%02x, %u dwords\n", i, op, count);
            break;
        }
        if (kind) {
            unsigned first = pm4->pm4[i + 1];
            for (unsigned r = 0; r + 1 < count; r++) {
                unsigned offset = base + (first + r) * 4;
                fprintf(stderr, "  %4u: %-7s 0x%05x %-36s = 0x%08x\n", i, kind, offset,
                        ac_get_register_name(info->gfx_level, info->family, offset),
                        pm4->pm4[i + 2 + r]);
                regs++;
            }
        }
        i += 1 + count;
    }
    fprintf(stderr, "== %s: %u packets, %u register writes\n\n", name, packets, regs);
}

int main(void)
{
    struct radeon_info info;
    describe(&info);
    struct ac_pm4_state *a = build(&info, true);
    info.has_clear_state = false; /* B: explicit register writes stand in for CLEAR_STATE */
    struct ac_pm4_state *b = build(&info, false);

    printf("/* Generated by oops-mesa tools/preamble-dump from the pinned Mesa (see dependencies.mk).\n"
           " * The command-stream preamble radeonsi emits for gfx_level GFX10, family GFX1013, with the\n"
           " * device fields stated in preamble_dump.c. Variant A opens with CONTEXT_CONTROL and\n"
           " * CLEAR_STATE; variant B is the same preamble for a device reported without CLEAR_STATE.\n"
           " * Data, not code: regenerate, do not edit. */\n"
           "#ifndef OOPS_MESA_PREAMBLE_GFX1013_H\n#define OOPS_MESA_PREAMBLE_GFX1013_H\n"
           "#include <stdint.h>\n\n");
    print_array("oops_mesa_preamble_a", a);
    print_array("oops_mesa_preamble_b", b);
    printf("#endif\n");
    print_decoded("oops_mesa_preamble_a", a);
    print_decoded("oops_mesa_preamble_b", b);
    ac_pm4_free_state(a);
    ac_pm4_free_state(b);
    return 0;
}
