#!/usr/bin/env bash
# Emit the C source of a probe archive: one empty definition per symbol obSCEne's import census
# records present on this platform.
#
# meson answers "does this function exist" by linking a program that takes its address. With
# this archive a probe answers whether a measurement on this console found the symbol; an
# unmeasured one reports absent and Mesa takes its portable path (cross-prospero.ini).
#
# The definitions are never called or linked into a running binary: a title resolves these
# names from the platform's exports at load. This script only writes C; build-mesa.sh compiles
# it in the container.
set -eu

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd "$HERE/.." && pwd)
OUT="$HERE/platform-stubs.c"

# obSCEne's census lives in its repository, beside this one in the collection.
OBSCENE="${OOPS_MESA_OBSCENE_SRC:-$ROOT/../obscene}"
CENSUS="$OBSCENE/data/hardware/ps5-imports.txt"

if [ ! -f "$CENSUS" ]; then
    echo "oops-mesa: no obSCEne import census at $CENSUS" >&2
    echo "  set OOPS_MESA_OBSCENE_SRC to the obscene checkout." >&2
    exit 1
fi

sweep=$(sed -n 's/^OBS|sweep|\([^|]*\).*/\1/p' "$CENSUS" | head -1)

# Names measured present by other means but absent from the census, each with its evidence.
# The census is a mine of symbol tables, so a missing name means nobody looked there.
#
#   clock_gettime   resolved in `libkernel` and `libSceLibcInternal` by obSCEne's payload-leg
#                   probe 017-posix/clock-symbols; the eboot-leg census resolver sees only two
#                   module handles on a native title and misses it.
SUPPLEMENT="clock_gettime"

{
    printf '/* Generated by oops-mesa toolchain/stage-platform-stubs.sh. Data, not code.\n'
    printf ' *\n'
    printf ' * One empty definition per symbol obSCEne recorded `present` in its import census\n'
    printf ' * of this platform. Linked only into meson probe programs, so that "does this\n'
    printf ' * function exist" is answered by a measurement rather than by a link flag. Never\n'
    printf ' * linked into anything that runs. Source: obscene/data/hardware/ps5-imports.txt\n'
    printf ' * (sweep %%s). */\n'
    printf '\n'
    # A -nostdlib executable needs an entry point; probe programs are never run.
    printf 'void _start(void);\nvoid _start(void) { }\n\n'
    { grep -oE "^OBS\|sym\|[A-Za-z][A-Za-z_0-9]*\|[A-Za-z_][A-Za-z_0-9]*\|present" "$CENSUS" \
          | awk -F'|' '{print $4}'
      printf '%s\n' $SUPPLEMENT
    } | sort -u \
      | awk '{printf "void %s(void);\nvoid __attribute__((weak)) %s(void) { }\n", $1, $1}'
} > "$OUT"

printf 'oops-mesa: wrote %s stub definitions to toolchain/platform-stubs.c (census sweep %s)\n' \
    "$(grep -c '^void __attribute__' "$OUT")" "${sweep:-unknown}"
