#!/usr/bin/env bash
# Stage the C-library headers Mesa compiles against into toolchain/sysroot/usr/include.
#
# The source is the FreeBSD checkout pinned in dependencies.mk (D004), read with `git archive`
# so its working tree, sparse-checkout configuration and orbistoun's harvest of it are
# untouched. It is a partial clone, so blobs outside its sparse cone are fetched from its origin
# once, on first use.
#
# FreeBSD's `include/Makefile` assembles `/usr/include` from several trees, not only
# `include/`; the layout below follows it:
#
#   include/*.h and its subdirectories   ->  usr/include/
#   LHDRS, nine headers from sys/sys     ->  usr/include/            (errno.h, fcntl.h, ...)
#   LDIRS, directories under sys/        ->  usr/include/<dir>/      (sys/, net/, netinet/, ...)
#   sys/amd64/include                    ->  usr/include/machine/
#   sys/x86/include                      ->  usr/include/x86/
#   lib/msun/src/math.h                  ->  usr/include/math.h      (it ships with libm)
#
# `./bin/oops-mesa build` runs this before it configures.
set -eu

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd "$HERE/.." && pwd)
SYSROOT="$HERE/sysroot"
INC="$SYSROOT/usr/include"   # where clang -target x86_64-unknown-freebsd --sysroot looks

PIN=$(sed -n 's/^SYSROOT_PIN *:= *//p' "$ROOT/dependencies.mk")
SRC_NAME=$(sed -n 's/^SYSROOT_SOURCE *:= *//p' "$ROOT/dependencies.mk")

# The checkout lives outside this repository; the variable matches orbistoun's for the same tree.
SRC="${OOPS_MESA_FREEBSD_SRC:-$ROOT/../../$SRC_NAME}"

if [ ! -d "$SRC/.git" ]; then
    echo "oops-mesa: no $SRC_NAME checkout at $SRC" >&2
    echo "  set OOPS_MESA_FREEBSD_SRC to it, or clone it beside the collection." >&2
    exit 1
fi

actual=$(git -C "$SRC" rev-parse HEAD)
if [ "$actual" != "$PIN" ]; then
    echo "oops-mesa: $SRC_NAME is at $actual, dependencies.mk pins $PIN" >&2
    echo "  the headers Mesa compiles against are part of the build's identity (D004)." >&2
    exit 1
fi

# Verbatim from include/Makefile at the pin. Repeated rather than parsed, because a failed parse
# looks like an empty list; the check below catches drift.
LHDRS="aio.h errno.h fcntl.h linker_set.h poll.h stdatomic.h stdint.h syslog.h ucontext.h"
LDIRS="net netinet sys vm"

makefile_lhdrs=$(git -C "$SRC" show "$PIN:include/Makefile" \
    | sed -n '/^LHDRS=/,/^$/p' | sed 's/^LHDRS=//' | tr -d '\\\n\t' | tr -s ' ')
for h in $LHDRS; do
    case " $makefile_lhdrs " in
        *" $h "*) ;;
        *) echo "oops-mesa: include/Makefile no longer links $h; re-read its LHDRS" >&2; exit 1 ;;
    esac
done

# extract <tree path> <destination under usr/include>
extract() {
    local from="$1" to="$2" strip
    strip=$(printf '%s' "$from" | awk -F/ '{print NF}')
    mkdir -p "$INC/$to"
    git -C "$SRC" archive "$PIN" "$from" | tar -x -C "$INC/$to" --strip-components="$strip"
}

rm -rf "$SYSROOT"
mkdir -p "$INC"

extract include            .
extract sys/amd64/include  machine
extract sys/x86/include    x86
for d in $LDIRS; do extract "sys/$d" "$d"; done

# The nine headers include/Makefile links out of sys/sys rather than shipping itself.
for h in $LHDRS; do
    [ -f "$INC/sys/$h" ] && cp "$INC/sys/$h" "$INC/$h"
done

# math.h ships with msun, not include/; amd64 uses the generic variant.
git -C "$SRC" archive "$PIN" lib/msun/src/math.h | tar -x -C "$INC" --strip-components=3

# Other architectures inside include/, and every non-header file the source trees carry.
rm -rf "$INC/arm" "$INC/i386"
find "$INC" -type f ! -name '*.h' -delete
find "$INC" -type d -empty -delete

# osreldate.h is generated, not shipped: include/mk-osreldate.sh writes the one number from
# sys/sys/param.h. libelf's portability header includes it.
osreldate=$(sed -n 's/^#define[[:space:]]*__FreeBSD_version[[:space:]]*\([0-9]*\).*/\1/p' \
    "$INC/sys/param.h" | head -1)
if [ -z "$osreldate" ]; then
    echo "oops-mesa: no __FreeBSD_version in sys/param.h; cannot generate osreldate.h" >&2
    exit 1
fi
cat > "$INC/osreldate.h" <<EOF
/* Generated by oops-mesa toolchain/stage-sysroot.sh, as FreeBSD's include/mk-osreldate.sh
 * generates it: the one version number out of sys/sys/param.h at the pinned revision. */
#ifdef _KERNEL
#error "osreldate.h must not be used in the kernel, use sys/param.h"
#else
#undef __FreeBSD_version
#define __FreeBSD_version $osreldate
#endif
EOF

# The libc++ headers from the same pinned tree, for ACO, the ASTC tables and parts of Mesa's
# utility layer. `__config_site` and `__assertion_handler` are FreeBSD's generated pair from
# `lib/libc++`, which the headers require.
mkdir -p "$INC/c++/v1"
git -C "$SRC" archive "$PIN" contrib/llvm-project/libcxx/include \
    | tar -x -C "$INC/c++/v1" --strip-components=4
for f in __config_site __assertion_handler; do
    git -C "$SRC" show "$PIN:lib/libc++/$f" > "$INC/c++/v1/$f"
done

missing=""
for h in errno.h stdio.h stdlib.h string.h pthread.h math.h time.h fcntl.h stdint.h osreldate.h \
         c++/v1/cstdint c++/v1/mutex c++/v1/__config_site; do
    [ -f "$INC/$h" ] || missing="$missing $h"
done
if [ -n "$missing" ]; then
    echo "oops-mesa: staged sysroot is missing:$missing" >&2
    exit 1
fi

printf 'oops-mesa: staged %s headers into toolchain/sysroot from %s @ %s\n' \
    "$(find "$INC" -name '*.h' | wc -l | tr -d ' ')" "$SRC_NAME" "${PIN:0:12}"
